### ISSUE TITLE
官网落地页预览图片在暗黑模式下图片变成了底片效果

### ISSUE THREAD

**Issue by iyhub** [UllrAI/HeadShots.fun#1]
## 环境

MacOS 暗黑模式

## 问题描述

落地页的图片在暗黑模式下,图片变成了底片效果.

## 截图/重现路径

<img width="492" alt="image" src="https://github.com/user-attachments/assets/e21eb47f-3241-405c-8e0d-8175fb6f5109">
<img width="1248" alt="image" src="https://github.com/user-attachments/assets/44bf47f9-b015-43a1-8124-be315012ae53">
## 其他

感谢在 https://tierlify.com 提交产品,如有其他更多的更多的详细信息需要补充请和我联系.

**Comment by visoar** [comment]
Thank you for your feedback. 
I will fix this issue in the next version.

**Comment by visoar** [comment]
It has been corrected. Thanks again for your feedback.
已修正，再次感谢反馈。
